// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc5933.Caroline.subsystems;

import org.usfirst.frc5933.Caroline.Robot;
import org.usfirst.frc5933.Caroline.RobotMap;
import org.usfirst.frc5933.Caroline.commands.DefaultTeleopCommand;

import com.ctre.CANTalon;
import com.ctre.CANTalon.TalonControlMode;

import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class DriveTrainSystem extends Subsystem {
	public final static float kNominalVoltage = 0;
	public final static float kPeakVoltage = 12;

	private boolean in_low_gear_ = false;

	private final static boolean leftSideInverted = false;
	private final static boolean rightSideInverted = false;

<<<<<<< HEAD
	public final static double kLowGearMin = 0.6; //These are tested values. the set() uses a 0.0 - 1.0 range. DON'T CHANGE
	//public final static double kLowGearMax = 0.525; //these are intermediate guestimated values. is more like maxLooseness

	//public final static double kHighGearMin = 0.05; //believe me, these values work
	public final static double kHighGearMax = 0.085; //DON'T CHANGE
=======
	public final static double kLowGearMin = 0.6; // These are tested values.
													// the set() uses a 0.0 -
													// 1.0 range
	public final static double kLowGearMax = 0.525; // these are intermediate
													// guestimated values. is
													// more like maxLooseness

	public final static double kHighGearMin = 0.05; // believe me, these values
													// work
	public final static double kHighGearMax = 0.085; // DON'T CHANGE
>>>>>>> origin/master

	private final CANTalon leftSlave1Motor = RobotMap.driveTrainSystemLeftSlaveMotor1;
	private final CANTalon leftSlave2Motor = RobotMap.driveTrainSystemLeftSlaveMotor2;

	private final CANTalon rightSlave1Motor = RobotMap.driveTrainSystemRightSlaveMotor1;
	private final CANTalon rightSlave2Motor = RobotMap.driveTrainSystemRightSlaveMotor2;

	private final static double kMaximumMagnitudePercentVBusShudder = 9.0;
	private final static double kMinimumMagnitudePercentVBusShudder = 2.0;

<<<<<<< HEAD
	private final static double kVBusShudderIncrement = 0.1; //the incrementing step. generally 0.1
=======
	private final static double kVBusShudderIncrement = 0.1; // the incrementing
																// step.
																// generally 0.1
>>>>>>> origin/master

	private double shudderMagnitude = 0.5;

	public DriveTrainSystem() {
		super();

	}

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	private final CANTalon leftMasterMotor = RobotMap.driveTrainSystemLeftMasterMotor;
	private final CANTalon rightMasterMotor = RobotMap.driveTrainSystemRightMasterMotor;
	private final RobotDrive robotDrive = RobotMap.driveTrainSystemRobotDrive;
	private final Servo leftShifter = RobotMap.driveTrainSystemLeftShifter;
	private final Servo rightShifter = RobotMap.driveTrainSystemRightShifter;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		setDefaultCommand(new DefaultTeleopCommand());

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	public void robotInit() {
		configVoltages(kNominalVoltage, kPeakVoltage);
		configReversed(leftSideInverted, rightSideInverted);
		configFollower();
	}

	public void teleopInit() {
		SmartDashboard.putNumber("Shudder Magnitude:", shudderMagnitude);
		enableBrakeMode(false);
	}

	public void autonomousInit() {
		enableBrakeMode(true);
	}

	public void set(double left, double right) {
		leftMasterMotor.set(left);
		rightMasterMotor.set(right);
	}

	public void stop() {
		robotDrive.stopMotor();
	}

	public void arcadeDrive(GenericHID joystick) {
		robotDrive.arcadeDrive(joystick);
	}

	public void arcadeDrive(double moveValue, double rotateValue) {
		robotDrive.arcadeDrive(moveValue, rotateValue);
	}

	public void tankDrive(double leftValue, double rightValue) {
		robotDrive.tankDrive(leftValue, rightValue);
	}

	private void enableBrakeMode(boolean enable) {
		leftMasterMotor.enableBrakeMode(enable);
		rightMasterMotor.enableBrakeMode(enable);
		leftSlave1Motor.enableBrakeMode(enable);
		leftSlave2Motor.enableBrakeMode(enable);
		rightSlave1Motor.enableBrakeMode(enable);
		rightSlave2Motor.enableBrakeMode(enable);
	}

	private void configVoltages(float nominal, double peak) {
		leftMasterMotor.changeControlMode(TalonControlMode.PercentVbus);
		leftMasterMotor.configNominalOutputVoltage(nominal, -nominal);
		leftMasterMotor.configPeakOutputVoltage(peak, -peak);

		rightMasterMotor.changeControlMode(TalonControlMode.PercentVbus);
		rightMasterMotor.configNominalOutputVoltage(nominal, -nominal);
		rightMasterMotor.configPeakOutputVoltage(peak, -peak);

<<<<<<< HEAD
		if (!Robot.is_sonny) {
			leftSlave1Motor.changeControlMode(TalonControlMode.PercentVbus);
			leftSlave1Motor.configNominalOutputVoltage(nominal, -nominal);
			leftSlave1Motor.configPeakOutputVoltage(peak, -peak);

			leftSlave2Motor.changeControlMode(TalonControlMode.PercentVbus);
			leftSlave2Motor.configNominalOutputVoltage(nominal, -nominal);
			leftSlave2Motor.configPeakOutputVoltage(peak, -peak);

			rightSlave1Motor.changeControlMode(TalonControlMode.PercentVbus);
			rightSlave1Motor.configNominalOutputVoltage(nominal, -nominal);
			rightSlave1Motor.configPeakOutputVoltage(peak, -peak);

			rightSlave2Motor.changeControlMode(TalonControlMode.PercentVbus);
			rightSlave2Motor.configNominalOutputVoltage(nominal, -nominal);
			rightSlave2Motor.configPeakOutputVoltage(peak, -peak);
		}
	}

	private void configReversed(boolean leftInvert, boolean rightInvert){
=======
		leftSlave1Motor.changeControlMode(TalonControlMode.PercentVbus);
		leftSlave1Motor.configNominalOutputVoltage(nominal, -nominal);
		leftSlave1Motor.configPeakOutputVoltage(peak, -peak);

		leftSlave2Motor.changeControlMode(TalonControlMode.PercentVbus);
		leftSlave2Motor.configNominalOutputVoltage(nominal, -nominal);
		leftSlave2Motor.configPeakOutputVoltage(peak, -peak);

		rightSlave1Motor.changeControlMode(TalonControlMode.PercentVbus);
		rightSlave1Motor.configNominalOutputVoltage(nominal, -nominal);
		rightSlave1Motor.configPeakOutputVoltage(peak, -peak);

		rightSlave2Motor.changeControlMode(TalonControlMode.PercentVbus);
		rightSlave2Motor.configNominalOutputVoltage(nominal, -nominal);
		rightSlave2Motor.configPeakOutputVoltage(peak, -peak);
	}

	private void configReversed(boolean leftInvert, boolean rightInvert) {
>>>>>>> origin/master
		leftMasterMotor.setInverted(leftInvert);
		rightMasterMotor.setInverted(rightInvert);
	}

	private void configFollower() {
<<<<<<< HEAD
		if (!Robot.is_sonny) {
			leftSlave1Motor.changeControlMode(TalonControlMode.Follower);
			leftSlave1Motor.set(leftMasterMotor.getDeviceID()); // tells the
			// follower
			// which master
			// to follow.
			leftSlave2Motor.changeControlMode(TalonControlMode.Follower);
			leftSlave2Motor.set(leftMasterMotor.getDeviceID()); // tells the
			// follower
			// which master
			// to follow.
			rightSlave1Motor.changeControlMode(TalonControlMode.Follower);
			rightSlave1Motor.set(rightMasterMotor.getDeviceID()); // tells the
			// follower
			// which
			// master to
			// follow.
			rightSlave2Motor.changeControlMode(TalonControlMode.Follower);
			rightSlave2Motor.set(rightMasterMotor.getDeviceID()); // tells the
			// follower
			// which
			// master to
			// follow.
		}
	}

	private void adjustGearing() { //low goes to high and high goes to low. Automagically.
=======
		leftSlave1Motor.changeControlMode(TalonControlMode.Follower);
		leftSlave1Motor.set(leftMasterMotor.getDeviceID());
		leftSlave2Motor.changeControlMode(TalonControlMode.Follower);
		leftSlave2Motor.set(leftMasterMotor.getDeviceID());
		rightSlave1Motor.changeControlMode(TalonControlMode.Follower);
		rightSlave1Motor.set(rightMasterMotor.getDeviceID());
		rightSlave2Motor.changeControlMode(TalonControlMode.Follower);
		rightSlave2Motor.set(rightMasterMotor.getDeviceID());
	}

	private void adjustGearing() { // low goes to high and high goes to low.
									// Automagically.
>>>>>>> origin/master
		SmartDashboard.putBoolean("In Low Gear: ", inLowGear());
		if (inLowGear()) {
			leftShifter.set(kLowGearMin); // this should work without feedback
			rightShifter.set(kLowGearMin);
		} else {
			leftShifter.set(kHighGearMax);
			rightShifter.set(kHighGearMax);
		}
<<<<<<< HEAD
		//		boolean left_is_done = false;							//the servos do not return a value. This code cannot work without a separate port with a pot.
		//		boolean right_is_done = false;
		//		if (inLowGear()) { //always maintains a gear during match
		//			double leftAngle = leftShifter.getAngle(); 
		//			if (!(leftAngle >= kLowGearMin) && !(leftAngle <= kLowGearMax)) {
		//				leftShifter.set((kLowGearMax - kLowGearMin) / 2);
		//			} else {
		//				left_is_done = true;
		//			}
		//
		//			double rightAngle = rightShifter.getAngle(); 
		//			if (!(rightAngle >= kLowGearMin) && !(rightAngle <= kLowGearMax)) {
		//				rightShifter.set((kLowGearMax - kLowGearMin) / 2);
		//			} else {
		//				right_is_done = true;
		//			}
		//			is_shifting_ = !(left_is_done && right_is_done);
		//		} else {
		//			double leftAngle = leftShifter.getAngle(); 
		//			if (!(leftAngle >= kHighGearMin) && !(leftAngle <= kHighGearMax)) {
		//				leftShifter.set((kHighGearMax - kHighGearMin) / 2);
		//			} else {
		//				left_is_done = true;
		//			}
		//
		//			double rightAngle = rightShifter.getAngle(); 
		//			if (!(rightAngle >= kHighGearMin) && !(rightAngle <= kHighGearMax)) {
		//				rightShifter.set((kHighGearMax - kHighGearMin) / 2);
		//			} else {
		//				right_is_done = true;
		//			}
		//			is_shifting_ = !(left_is_done && right_is_done);
		//		}
=======
>>>>>>> origin/master
	}

	public void teleopPeriodic() {
		adjustGearing();
	}

	public void autonomousPeriodic() {
		adjustGearing();
	}

	public boolean inLowGear() {
		return in_low_gear_;
	}

	public void shift() {
<<<<<<< HEAD
		//if (is_shifting_) //we can't use this without encoder feedback from servos
		//	return;

		//is_shifting_ = true;
		in_low_gear_ = !in_low_gear_;
	}
	// RESOLVED: Test out GearShifting and make sure that the angles for the servos work. Constants changed at top 2/11/17

=======
		in_low_gear_ = !in_low_gear_;
	}
>>>>>>> origin/master

	public void shudder_left() {
		set(-shudderMagnitude, shudderMagnitude);
	}

	public void shudder_right() {
		set(shudderMagnitude, -shudderMagnitude);
	}

<<<<<<< HEAD
	public void incrementShudder(){ //slight logic change, first change it, then test how large/small it is. Should be foolproof now.
		shudderMagnitude += kVBusShudderIncrement;

		if(shudderMagnitude > kMaximumMagnitudePercentVBusShudder)
			shudderMagnitude = kMaximumMagnitudePercentVBusShudder;

		SmartDashboard.putNumber("Shudder Magnitude:", shudderMagnitude);
	}

	public void decrementShudder(){ //same change as above.
		shudderMagnitude -= kVBusShudderIncrement;

		if(shudderMagnitude < kMinimumMagnitudePercentVBusShudder)
			shudderMagnitude = kMinimumMagnitudePercentVBusShudder;
=======
	public void incrementShudder() {
		if (shudderMagnitude > kMaximumMagnitudePercentVBusShudder) {
			shudderMagnitude = kMaximumMagnitudePercentVBusShudder;
		} else {
			shudderMagnitude += kVBusShudderIncrement;
		}
		SmartDashboard.putNumber("Shudder Magnitude:", shudderMagnitude);
	}

	public void decrementShudder() {
		if (shudderMagnitude < kMinimumMagnitudePercentVBusShudder) {
			shudderMagnitude = kMinimumMagnitudePercentVBusShudder;
		} else {
			shudderMagnitude -= kVBusShudderIncrement;
		}
>>>>>>> origin/master
		SmartDashboard.putNumber("Shudder Magnitude:", shudderMagnitude);
	}
}
