// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5933.Caroline;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController gearCollectionSystemFrontFlapper;
    public static SpeedController gearCollectionSystemBackFlapper;
    public static CANTalon climbingClimbingSpindle;
    public static SpeedController climbingClimbingClaw;
    public static CANTalon flyWheelWheelMotor;
    public static CANTalon ballColledtionSystemElevatorMotor;
    public static CANTalon ballColledtionSystemVacuumMotor;
    public static CANTalon hopperAgitiator;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        gearCollectionSystemFrontFlapper = new Spark(0);
        LiveWindow.addActuator("GearCollectionSystem", "FrontFlapper", (Spark) gearCollectionSystemFrontFlapper);
        
        gearCollectionSystemBackFlapper = new Spark(1);
        LiveWindow.addActuator("GearCollectionSystem", "BackFlapper", (Spark) gearCollectionSystemBackFlapper);
        
        climbingClimbingSpindle = new CANTalon(6);
        LiveWindow.addActuator("Climbing", "ClimbingSpindle", climbingClimbingSpindle);
        
        climbingClimbingClaw = new Spark(2);
        LiveWindow.addActuator("Climbing", "ClimbingClaw", (Spark) climbingClimbingClaw);
        
        flyWheelWheelMotor = new CANTalon(7);
        LiveWindow.addActuator("FlyWheel", "WheelMotor", flyWheelWheelMotor);
        
        ballColledtionSystemElevatorMotor = new CANTalon(8);
        LiveWindow.addActuator("BallColledtionSystem", "ElevatorMotor", ballColledtionSystemElevatorMotor);
        
        ballColledtionSystemVacuumMotor = new CANTalon(9);
        LiveWindow.addActuator("BallColledtionSystem", "VacuumMotor", ballColledtionSystemVacuumMotor);
        
        hopperAgitiator = new CANTalon(10);
        LiveWindow.addActuator("Hopper", "Agitiator", hopperAgitiator);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
